[build]
builder = "nixpacks"

[deploy]
startCommand = "cd witnessos-engines && uvicorn app:app --host 0.0.0.0 --port $PORT --workers 2"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
