name = "witnessos-backend"
main = "src/workers/index.ts"
compatibility_date = "2024-01-15"

[env.production]
name = "witnessos-backend-prod"
routes = [
  { pattern = "api.witnessos.com/*", zone_name = "witnessos.com" }
]

[env.staging]
name = "witnessos-backend-staging"
routes = [
  { pattern = "api-staging.witnessos.com/*", zone_name = "witnessos.com" }
]

# KV Namespaces - Production
[[env.production.kv_namespaces]]
binding = "ENGINE_DATA"
id = "ENGINE_DATA_PROD_ID"  # Replace with actual KV namespace ID

[[env.production.kv_namespaces]]
binding = "USER_PROFILES"
id = "USER_PROFILES_PROD_ID"  # Replace with actual KV namespace ID

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "CACHE_PROD_ID"  # Replace with actual KV namespace ID

# KV Namespaces - Staging
[[env.staging.kv_namespaces]]
binding = "ENGINE_DATA"
id = "ENGINE_DATA_STAGING_ID"  # Replace with actual KV namespace ID

[[env.staging.kv_namespaces]]
binding = "USER_PROFILES"
id = "USER_PROFILES_STAGING_ID"  # Replace with actual KV namespace ID

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "CACHE_STAGING_ID"  # Replace with actual KV namespace ID

# Environment Variables - Production
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
CORS_ORIGIN = "*"
RATE_LIMIT_MAX = "1000"
RATE_LIMIT_WINDOW = "60000"

# Environment Variables - Staging
[env.staging.vars]
ENVIRONMENT = "staging"
API_VERSION = "1.0.0-staging"
CORS_ORIGIN = "*"
RATE_LIMIT_MAX = "100"
RATE_LIMIT_WINDOW = "60000"

# Scheduled Events for Cache Cleanup
[[env.production.triggers.crons]]
cron = "0 0 * * *"  # Daily at midnight UTC

[[env.staging.triggers.crons]]
cron = "0 2 * * *"  # Daily at 2 AM UTC

# Build Configuration - Skip frontend build for Workers
[build]
command = "echo 'Skipping frontend build for Workers deployment'"

# Development Configuration
[env.development]
compatibility_date = "2024-01-15"

[[env.development.kv_namespaces]]
binding = "ENGINE_DATA"
preview_id = "ENGINE_DATA_DEV_ID"

[[env.development.kv_namespaces]]
binding = "USER_PROFILES"
preview_id = "USER_PROFILES_DEV_ID"

[[env.development.kv_namespaces]]
binding = "CACHE"
preview_id = "CACHE_DEV_ID"

[env.development.vars]
ENVIRONMENT = "development"
API_VERSION = "1.0.0-dev"
CORS_ORIGIN = "*"
RATE_LIMIT_MAX = "50"
RATE_LIMIT_WINDOW = "60000" 