name = "witnessos-backend"
main = "src/workers/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "witnessos-db"
database_id = "36b03146-4184-45cc-9ed6-a24f0747cdb5"

[[r2_buckets]]
binding = "REPORTS"
bucket_name = "witnessos-reports"

# KV Namespaces - Default (Development)
[[kv_namespaces]]
binding = "ENGINE_DATA"
id = "317be7d22ee14e51b1bed3d15145dd51"

[[kv_namespaces]]
binding = "USER_PROFILES"
id = "6df29230ffca4e7c8299decdf0a2121f"

[[kv_namespaces]]
binding = "CACHE"
id = "d5aa9b42b2f948bfa59143d5a56ea58b"

# SECRETS namespace - configure if needed
# [[kv_namespaces]]
# binding = "SECRETS"
# id = "secrets_namespace_id_placeholder"

[env.production]
name = "witnessos-backend-prod"
routes = [
  { pattern = "api.witnessos.space/*", zone_id = "cf14b78dd6490cd4e21cd91af1ac7cb7" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "witnessos-db"
database_id = "36b03146-4184-45cc-9ed6-a24f0747cdb5"

[[env.production.r2_buckets]]
binding = "REPORTS"
bucket_name = "witnessos-reports"

[env.staging]
name = "witnessos-backend-staging"
routes = [
  { pattern = "api-staging.witnessos.space/*", zone_id = "cf14b78dd6490cd4e21cd91af1ac7cb7" }
]

# KV Namespaces - Production
[[env.production.kv_namespaces]]
binding = "ENGINE_DATA"
id = "317be7d22ee14e51b1bed3d15145dd51"

[[env.production.kv_namespaces]]
binding = "USER_PROFILES"
id = "6df29230ffca4e7c8299decdf0a2121f"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "d5aa9b42b2f948bfa59143d5a56ea58b"

# SECRETS namespace for API keys and sensitive configuration
[[env.production.kv_namespaces]]
binding = "SECRETS"
id = "74748736c9584954b5191d3ebe3300ac"

# KV Namespaces - Staging
[[env.staging.kv_namespaces]]
binding = "ENGINE_DATA"
id = "ENGINE_DATA_STAGING_ID"  # Replace with actual KV namespace ID

[[env.staging.kv_namespaces]]
binding = "USER_PROFILES"
id = "USER_PROFILES_STAGING_ID"  # Replace with actual KV namespace ID

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "CACHE_STAGING_ID"  # Replace with actual KV namespace ID

[[env.staging.kv_namespaces]]
binding = "SECRETS"
id = "SECRETS_STAGING_ID"  # Replace with actual KV namespace ID

# Environment Variables - Production
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
CORS_ORIGIN = "*"
RATE_LIMIT_MAX = "1000"
RATE_LIMIT_WINDOW = "60000"
JWT_SECRET = "7f9a2b5d0c3e8f1a6d9b4c7e5f2a1b0d9c8e7f6a5b4d3c2e1f0a9b8c7d6e5f4"
OPENROUTER_API_KEY = ""

# AI Enhancement (Optional) - Set as secret:
# wrangler secret put OPENROUTER_API_KEY --env production

# Environment Variables - Staging
[env.staging.vars]
ENVIRONMENT = "staging"
API_VERSION = "1.0.0-staging"
CORS_ORIGIN = "*"
RATE_LIMIT_MAX = "100"
RATE_LIMIT_WINDOW = "60000"
JWT_SECRET = "c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2d1e0f9a8b7c6d5e4f3e2d1c0b9a8e7f6"

# Scheduled Events for Cache Cleanup (disabled for now)
# [[env.production.triggers.crons]]
# cron = "0 0 * * *"  # Daily at midnight UTC

# [[env.staging.triggers.crons]]
# cron = "0 2 * * *"  # Daily at 2 AM UTC

# Build Configuration - Skip frontend build for Workers
[build]
command = "echo 'Skipping frontend build for Workers deployment'"

# Development Configuration
[env.development]
compatibility_date = "2024-01-15"

[[env.development.kv_namespaces]]
binding = "ENGINE_DATA"
id = "317be7d22ee14e51b1bed3d15145dd51"

[[env.development.kv_namespaces]]
binding = "USER_PROFILES"
id = "6df29230ffca4e7c8299decdf0a2121f"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "d5aa9b42b2f948bfa59143d5a56ea58b"

[env.development.vars]
ENVIRONMENT = "development"
API_VERSION = "1.0.0-dev"
CORS_ORIGIN = "*"
RATE_LIMIT_MAX = "50"
RATE_LIMIT_WINDOW = "60000"
JWT_SECRET = "1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3e2d1c0b9a8f7e6d5c4b3a2d1e0f"

# Cloudflare Pages Configuration
pages_build_output_dir = "dist"

# Rate Limiting - CPU limits not available on free plan
# [limits]
# cpu_ms = 10000