# Test Configuration for Enhanced Architecture
# Simplified version without service bindings for testing

name = "witnessos-backend"
main = "src/workers/test-index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "witnessos-db"
database_id = "36b03146-4184-45cc-9ed6-a24f0747cdb5"

# R2 Buckets
[[r2_buckets]]
binding = "REPORTS"
bucket_name = "witnessos-reports"

# KV Namespaces
[[kv_namespaces]]
binding = "ENGINE_DATA"
id = "317be7d22ee14e51b1bed3d15145dd51"

[[kv_namespaces]]
binding = "USER_PROFILES"
id = "b8e4d5c6f7a8b9c0d1e2f3a4b5c6d7e8"

[[kv_namespaces]]
binding = "FORECAST_CACHE"
id = "c9f5e6d7a8b9c0d1e2f3a4b5c6d7e8f9"

[[kv_namespaces]]
binding = "ENGINE_CACHE"
id = "d0a6f7e8b9c0d1e2f3a4b5c6d7e8f9a0"

[[kv_namespaces]]
binding = "AI_CACHE"
id = "e1b7a8f9c0d1e2f3a4b5c6d7e8f9a0b1"

# Environment Variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "2.0"
ENABLE_CACHING = "true"
ENABLE_ANALYTICS = "true"

# Production environment
[env.production]
name = "witnessos-backend-prod"

# D1 Database for production
[[env.production.d1_databases]]
binding = "DB"
database_name = "witnessos-db"
database_id = "36b03146-4184-45cc-9ed6-a24f0747cdb5"

# R2 Buckets for production
[[env.production.r2_buckets]]
binding = "REPORTS"
bucket_name = "witnessos-reports"

# KV Namespaces for production
[[env.production.kv_namespaces]]
binding = "ENGINE_DATA"
id = "317be7d22ee14e51b1bed3d15145dd51"

[[env.production.kv_namespaces]]
binding = "USER_PROFILES"
id = "6df29230ffca4e7c8299decdf0a2121f"

[[env.production.kv_namespaces]]
binding = "FORECAST_CACHE"
id = "d5aa9b42b2f948bfa59143d5a56ea58b"

[[env.production.kv_namespaces]]
binding = "ENGINE_CACHE"
id = "d5aa9b42b2f948bfa59143d5a56ea58b"

[[env.production.kv_namespaces]]
binding = "AI_CACHE"
id = "d5aa9b42b2f948bfa59143d5a56ea58b"

# Environment Variables for production
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "2.0"
ENABLE_CACHING = "true"
ENABLE_ANALYTICS = "true"
JWT_SECRET = "witnessos-jwt-secret-2025"
