# Enhanced WitnessOS API Router Configuration
# Main orchestration worker with service bindings to specialized workers

name = "witnessos-api-router"
main = "src/workers/enhanced-api-router.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Service bindings to specialized workers (RPC)
[[services]]
binding = "ENGINE_SERVICE"
service = "witnessos-engine-service"

[[services]]
binding = "FORECAST_SERVICE"
service = "witnessos-forecast-service"

[[services]]
binding = "AI_SERVICE"
service = "witnessos-ai-service"

# Durable Objects
[[durable_objects.bindings]]
name = "ENGINE_COORDINATOR"
class_name = "EngineCoordinator"
script_name = "witnessos-api-router"

[[durable_objects.bindings]]
name = "FORECAST_SESSION"
class_name = "ForecastSession"
script_name = "witnessos-api-router"

# Workflows
[[workflows]]
name = "CONSCIOUSNESS_WORKFLOW"
binding = "CONSCIOUSNESS_WORKFLOW"
class_name = "ConsciousnessWorkflow"

[[workflows]]
name = "INTEGRATION_WORKFLOW"
binding = "INTEGRATION_WORKFLOW"
class_name = "IntegrationWorkflow"

# KV Namespaces
[[kv_namespaces]]
binding = "KV_CACHE"
id = "your-cache-kv-namespace-id"
preview_id = "your-cache-kv-preview-id"

[[kv_namespaces]]
binding = "KV_USER_PROFILES"
id = "your-profiles-kv-namespace-id"
preview_id = "your-profiles-kv-preview-id"

[[kv_namespaces]]
binding = "KV_FORECASTS"
id = "your-forecasts-kv-namespace-id"
preview_id = "your-forecasts-kv-preview-id"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "witnessos-db"
database_id = "your-database-id"

# Environment Variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "2.0"
ENABLE_CACHING = "true"
ENABLE_ANALYTICS = "true"

# Secrets (set via wrangler secret put)
# JWT_SECRET
# OPENROUTER_API_KEY

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_sqlite_classes = ["EngineCoordinator", "ForecastSession"]

# Routes
[[routes]]
pattern = "api.witnessos.com/*"
zone_name = "witnessos.com"

# Build configuration
[build]
command = "npm run build"

# Development configuration
[env.development]
name = "witnessos-api-router-dev"

[env.development.vars]
ENVIRONMENT = "development"
ENABLE_CACHING = "false"

# Staging configuration
[env.staging]
name = "witnessos-api-router-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

# Production configuration
[env.production]
name = "witnessos-api-router-prod"

[env.production.vars]
ENVIRONMENT = "production"
ENABLE_ANALYTICS = "true"
